// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamowoAPI.Data;

#nullable disable

namespace SteamowoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716065310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SteamowoAPI.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataWydania")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlOkladki")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cena = 49.99m,
                            DataWydania = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "RPG",
                            Opis = "Klasyk RPG od CD Projekt Red.",
                            Producent = "CD Projekt Red",
                            Tytul = "Wiedzmin 3: Dziki Gon",
                            UrlOkladki = "https://picsum.photos/seed/steamowo1/300/400"
                        },
                        new
                        {
                            Id = 2,
                            Cena = 0m,
                            DataWydania = new DateTime(2023, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "FPS",
                            Opis = "Kultowa strzelanka druzynowa.",
                            Producent = "Valve",
                            Tytul = "Counter Strike 2",
                            UrlOkladki = "https://picsum.photos/seed/steamowo2/300/400"
                        },
                        new
                        {
                            Id = 3,
                            Cena = 29.99m,
                            DataWydania = new DateTime(2016, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Symulator",
                            Opis = "Relaksujaca gra farmerska.",
                            Producent = "ConcernedApe",
                            Tytul = "Stardew Valley",
                            UrlOkladki = "https://picsum.photos/seed/steamowo3/300/400"
                        },
                        new
                        {
                            Id = 4,
                            Cena = 199.99m,
                            DataWydania = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "RPG/Akcja",
                            Opis = "Trudne souls-like w otwartym swiecie.",
                            Producent = "FromSoftware",
                            Tytul = "Elden Ring",
                            UrlOkladki = "https://picsum.photos/seed/steamowo4/300/400"
                        },
                        new
                        {
                            Id = 5,
                            Cena = 149.99m,
                            DataWydania = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "RPG/Akcja",
                            Opis = "Futurystyczne RPG akcji w Night City.",
                            Producent = "CD Projekt Red",
                            Tytul = "Cyberpunk 2077",
                            UrlOkladki = "https://picsum.photos/seed/steamowo5/300/400"
                        },
                        new
                        {
                            Id = 6,
                            Cena = 99.99m,
                            DataWydania = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja",
                            Opis = "Otwarty swiat przestepczosci w Los Santos.",
                            Producent = "Rockstar Games",
                            Tytul = "Grand Theft Auto V",
                            UrlOkladki = "https://picsum.photos/seed/steamowo6/300/400"
                        },
                        new
                        {
                            Id = 7,
                            Cena = 89.99m,
                            DataWydania = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Sandbox",
                            Opis = "Buduj i eksploruj w swiecie z klockow.",
                            Producent = "Mojang",
                            Tytul = "Minecraft",
                            UrlOkladki = "https://picsum.photos/seed/steamowo7/300/400"
                        },
                        new
                        {
                            Id = 8,
                            Cena = 0m,
                            DataWydania = new DateTime(2013, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "MOBA",
                            Opis = "Darmowa gra MOBA od Valve.",
                            Producent = "Valve",
                            Tytul = "Dota 2",
                            UrlOkladki = "https://picsum.photos/seed/steamowo8/300/400"
                        },
                        new
                        {
                            Id = 9,
                            Cena = 39.99m,
                            DataWydania = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Platformowa",
                            Opis = "Klimatyczna metroidvania w podziemnym swiecie.",
                            Producent = "Team Cherry",
                            Tytul = "Hollow Knight",
                            UrlOkladki = "https://picsum.photos/seed/steamowo9/300/400"
                        },
                        new
                        {
                            Id = 10,
                            Cena = 249.99m,
                            DataWydania = new DateTime(2023, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Sportowa",
                            Opis = "Symulator pilki noznej.",
                            Producent = "EA Sports",
                            Tytul = "FIFA 24",
                            UrlOkladki = "https://picsum.photos/seed/steamowo10/300/400"
                        },
                        new
                        {
                            Id = 11,
                            Cena = 219.99m,
                            DataWydania = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "RPG",
                            Opis = "Rozbudowane RPG oparte na D&D.",
                            Producent = "Larian Studios",
                            Tytul = "Baldur's Gate 3",
                            UrlOkladki = "https://picsum.photos/seed/steamowo11/300/400"
                        },
                        new
                        {
                            Id = 12,
                            Cena = 0m,
                            DataWydania = new DateTime(2015, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Sportowa/Akcja",
                            Opis = "Pilka nozna samochodami.",
                            Producent = "Psyonix",
                            Tytul = "Rocket League",
                            UrlOkladki = "https://picsum.photos/seed/steamowo12/300/400"
                        });
                });

            modelBuilder.Entity("SteamowoAPI.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<decimal>("Kwota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SteamowoAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SaldoPortfela")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SteamowoAPI.Models.UserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaZakupu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("CzasGry")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataZakupu")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("SteamowoAPI.Models.Transaction", b =>
                {
                    b.HasOne("SteamowoAPI.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SteamowoAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteamowoAPI.Models.UserGame", b =>
                {
                    b.HasOne("SteamowoAPI.Models.Game", "Game")
                        .WithMany("Wlasciciele")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamowoAPI.Models.User", "User")
                        .WithMany("PosiadaneGry")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteamowoAPI.Models.Game", b =>
                {
                    b.Navigation("Wlasciciele");
                });

            modelBuilder.Entity("SteamowoAPI.Models.User", b =>
                {
                    b.Navigation("PosiadaneGry");
                });
#pragma warning restore 612, 618
        }
    }
}
